[Mellanox] Allow flexible setting of I2C transactions
Azure/sonic-linux-kernel pull request #156
Opened 2020-08-10 14:42 UTC by volodymyrsamotiy

* Upstream commit details:

  commit 3029a693beda5bff599feccc3beb9df1e141c786
  Author: Vadim Pasternak <vadimp@mellanox.com>
  Date:   Wed May 29 11:47:16 2019 +0300

      mlxsw: i2c: Allow flexible setting of I2C transactions size

      Current implementation uses fixed size of I2C data transaction buffer.
      Allow to set size of I2C transactions according to I2C physical adapter
      capability. For that purpose adapter read and write size is obtained
      from the I2C physical adapter and buffer size is set according to the
      minimum of these two values. If adapter does not provide such info,
      default buffer size is to be used.
      It allows to improve performance of I2C access to silicon when long
      size transactions are used.

      Signed-off-by: Vadim Pasternak <vadimp@mellanox.com>
      Acked-by: Jiri Pirko <jiri@mellanox.com>
      Signed-off-by: Ido Schimmel <idosch@mellanox.com>
      Signed-off-by: David S. Miller <davem@davemloft.net>

Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

2020-08-13 08:36 UTC, liat-grozovik commented
@lguhan can you please review and merge? we need it to overcome master pmon issue.

2020-08-13 15:55 UTC, lguohan commented
please put the upstream commit in the patch commit message.

2020-08-13 15:59 UTC, liat-grozovik commented
this is the commit message of the upstream code: 3029a693beda5bff599feccc3beb9df1e141c786

2020-08-30 14:11 UTC, liat-grozovik commented
@lguohan it is urgent for us to take merge it to master. Please help to merge.

2020-08-31 18:14 UTC, lguohan commented
i cannot find the upstream commit id in the patch commit message.

2020-09-02 15:53 UTC, liat-grozovik commented
@lguohan 
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3029a693beda5bff599feccc3beb9df1e141c786
it's in master / net / net-next (old commit)

what else is missing?

2020-09-26 14:51 UTC, lguohan requested changes
please put upstream commit id in the patch message.

2020-09-30 10:09 UTC, closed without merging