NPU disable unused PCIe BAR
Azure/sonic-linux-kernel pull request #225
Opened 2021-07-01 03:06 UTC by msiddare

NPU device enumeration was failing because of an issue in the cisco
ASIC. This patch will fix address the issue by disabling unused BAR.

Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

2021-07-05 08:03 UTC, paulmenzel reviewed
Thank you for your patches, but reviewing your submission takes too much time because they have so many formal errors. It’d be great, if you got acquainted with the Linux kernel development processes, and followed them.

2021-07-05 08:03 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> +    Signed-off-by: Subha Keshavaraj <subkesha@cisco.com>
It looks like you just copied the output from `git show`. Please create the patch with `git format-patch …`.

2021-07-05 08:03 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> +        Spitfire-pacific-disable-all-bars-other-than-0.patch
Please provide a git commit hash or URL for this patch.

2021-07-05 08:03 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++	int i;
This does not follow the Linux coding style. Please check patches with `checkpatch.pl` script in the Linux kernel.

2021-07-13 15:55 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++	int i;
Sorry, Firefox display issues in the browser.

2021-07-14 06:06 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> +
Please also paste the new log messages from one device to the commit message.

2021-07-14 06:06 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++			"Cisco Silicon One BAR %d %pR fixed up\n", i, r);
Maybe:

> Cisco Silicon One BAR %d %pR disabled due to NPU hardware bug

2021-08-16 21:41 UTC, msiddare commented
Review comments incorporated and updated series file as per meeting discussion

2021-08-16 22:47 UTC, paulmenzel requested changes
Please get it reviewed by the Linux subsystem maintainers.

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++	 * to the device. This is only a temporary fix for pacific ASIC
Maybe:

> Due to HW bug, Pacific device is misbehaving during rescan by not enumerating memory for that BAR. Work around it and verify, that during rescan memory gets assigned properly to the device.

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++	 * only
Is it really temporary?

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++DECLARE_PCI_FIXUP_HEADER(PCI_VENDOR_ID_SYNOPSYS, PCI_DEVICE_ID_LEABA_PACIFIC,
Why `PCI_VENDOR_ID_SYNOPSYS`?

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++static void silicon_one_fixup(struct pci_dev *dev)
I’d think, the function name needs to include `cisco` somehow.

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> +Subject: [PATCH] NPU disable unused PCI BAR
Please make it an upstreamable commit message summary ([How to Write a Git Commit Message][1]).

[1]: https://chris.beams.io/posts/git-commit/

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> +
Still open.

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++#define PCI_DEVICE_ID_LEABA_KRYPTON    0xa006
Should the macros go in some header file?

2021-08-16 22:47 UTC, paulmenzel commented on patch/cisco-npu-disable-other-bars.patch
> ++ * For Pacific A0, only BAR 0 is valid
Please add an errata document name and number for reference.

2021-09-21 22:56 UTC, msiddare commented
Closing this PR as issue is observed only on early P0 proto boards.

2021-09-21 22:56 UTC, closed without merging